### ISSUE TITLE
Infinite Loop Master - Wording issue

### ISSUE THREAD

**Issue by shelbycat** [TwilioQuest/twilioquest-javascript#12]
I'm in Chamber 3 of the Infinite Loop Master (East-most area) of the JavaScript Testing Lab, "JavaScript Lab: A Transformational Moment"

(I hope this is the right place to report this)

I noticed a problem with the name of the function we're meant to do.  It says to "mutate", when we're not changing the original array.  This terminology difference may lead to confusion.

The following overview statement matches the function we're meant to write:
> Learn to execute a chunk of code for every item in a JavaScript array, and return a new array of items as a result.

And this is the description:
> This function should take one argument - an array of strings to be transformed. Your mutate function should use the [array "map"](https://javascript.info/array-methods#map) function to take every string in the input array and convert it to ALL CAPS. Your function must then return the mutated array.

I tested it both ways...
- If I do not mutate the original array, but instead return a brand new array, leaving the original array intact, I succeed.
- If I do mutate the original array, change the values and return it directly, I succeed.

Although I understand that it may click a little faster to use the word "mutate" and pretend that we're changing the original array... that's not what the actual goal of the level's mechanics.  Even the use of the Array.prototype.map indicates that we are not modifying the original array, and that we're not mutating the array.

I think that this may lead to confusion for beginner developers (the target audience) later down the road.

**Comment by rmkubik** [comment]
I forgot to comment on this Issue originally. Thank you for opening this issue! This was a great suggestion. :-)
